{
 "title": "Hive Backend",
 "description": "Metrics of hive-backend-app",
 "tags": [
  "go",
  "pgxpool"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": "0.50, 0.90, 0.99" }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scraping metrics status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(requests_total{job=\"app\", type=\"http\", path!=\"\", path!=\"/metrics\"}[$__rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} | {{status}}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "req/m" } },
   "targets": [
    {
     "expr": "sum(increase(requests_total{job=\"app\", type=\"http\", path!=\"\", path!=\"/metrics\", status!=\"ok\"}[$__rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} | {{status}}"
    }
   ]
  },
  {
   "title": "Latency (quantile: ${quantile})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "repeat": "quantile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${quantile:raw}, sum(rate(response_time_seconds_bucket{job=\"app\", type=\"http\", path!=\"\", path!=\"/metrics\"}[$__rate_interval])) by (le, method, path, status))",
     "legendFormat": "{{method}} {{path}} | {{status}}"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Last GC time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{job=\"app\"} * 1000",
     "legendFormat": "Last GC time"
    }
   ]
  },
  {
   "title": "Elapsed since last GC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "($__to - go_memstats_last_gc_time_seconds{job=\"app\"} * 1000)/1000",
     "legendFormat": "Elapsed since last GC"
    }
   ]
  },
  {
   "title": "GC execution rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_memstats_last_gc_time_seconds{job=\"app\"}[$__rate_interval])",
     "legendFormat": "TImeout"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"app\"}",
     "legendFormat": "{{quantile}} q"
    }
   ]
  },
  {
   "title": "Number of live objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mallocs_total{job=\"app\"} - go_memstats_frees_total{job=\"app\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of memory allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_mallocs_total{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Scheduler statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"app\"})",
     "legendFormat": "Threads count"
    },
    {
     "expr": "sum(go_goroutines{job=\"app\"})",
     "legendFormat": "Goroutines count"
    },
    {
     "expr": "sum(go_goroutines{job=\"app\"}) / sum(go_threads{job=\"app\"})",
     "legendFormat": "Goroutines/thread"
    }
   ]
  },
  {
   "title": "Pointer lookups",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(go_memstats_lookups_total{job=\"app\"}[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Stack memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=\"app\"})",
     "legendFormat": "In use"
    },
    {
     "expr": "sum(go_memstats_stack_sys_bytes{job=\"app\"})",
     "legendFormat": "Obtained from system"
    }
   ]
  },
  {
   "title": "Heap memory 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=\"app\"})",
     "legendFormat": "Allocated and still in use"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=\"app\"})",
     "legendFormat": "Obtained from system"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"app\"}",
     "legendFormat": "Waiting to be used"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=\"app\"})",
     "legendFormat": "Are in use"
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{job=\"app\"})",
     "legendFormat": "Released to system"
    }
   ]
  },
  {
   "title": "Go runtime memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes{job=\"app\"})",
     "legendFormat": "In use by mspan"
    },
    {
     "expr": "sum(go_memstats_mspan_sys_bytes{job=\"app\"})",
     "legendFormat": "Used for mspan obtained from system"
    },
    {
     "expr": "sum(go_memstats_mcache_inuse_bytes{job=\"app\"})",
     "legendFormat": "In use by mcache"
    },
    {
     "expr": "sum(go_memstats_mcache_sys_bytes{job=\"app\"})",
     "legendFormat": "Used for mcache obtained from system"
    },
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes{job=\"app\"})",
     "legendFormat": "Used by the profiling bucket hash table"
    },
    {
     "expr": "sum(go_memstats_gc_sys_bytes{job=\"app\"})",
     "legendFormat": "Used for GC system metadata"
    },
    {
     "expr": "sum(go_memstats_other_sys_bytes{job=\"app\"})",
     "legendFormat": "Used for other system allocations"
    },
    {
     "expr": "sum(go_memstats_next_gc_bytes{job=\"app\"})",
     "legendFormat": "When next GC will take place"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"app\"})",
     "legendFormat": "Obtained from system"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"app\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum(deriv(process_open_fds{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Rate"
    }
   ]
  },
  { "title": "PGX Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Number of database connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "sum(pgxpool_max_conns{job=\"app\"}) ",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(pgxpool_total_conns{job=\"app\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(pgxpool_constructing_conns{job=\"app\"}) ",
     "legendFormat": "Constructing"
    },
    {
     "expr": "sum(pgxpool_acquired_conns{job=\"app\"}) ",
     "legendFormat": "Acquired"
    },
    {
     "expr": "sum(pgxpool_idle_conns{job=\"app\"}) ",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Pool acquires rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pgxpool_acquire_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Acquired "
    },
    {
     "expr": "sum(rate(pgxpool_canceled_acquire_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Canceled"
    },
    {
     "expr": "sum(rate(pgxpool_empty_acquire{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Acquired from empty pool"
    },
    {
     "expr": "sum(rate(pgxpool_acquire_count{job=\"app\"}[$__rate_interval])) + sum(rate(pgxpool_canceled_acquire_count{job=\"app\"}[$__rate_interval])) + sum(rate(pgxpool_empty_acquire{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Delta number of connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(pgxpool_new_conns_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "New"
    },
    {
     "expr": "sum(delta(pgxpool_acquired_conns{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Acquired"
    },
    {
     "expr": "sum(increase(pgxpool_max_idle_destroy_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Exceeded idle time"
    },
    {
     "expr": "sum(increase(pgxpool_max_lifetime_destroy_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Exceeded life time"
    }
   ]
  },
  {
   "title": "Average connection acquire time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(pgxpool_acquire_duration_ns{job=\"app\"}[$__rate_interval])) / sum(rate(pgxpool_acquire_count{job=\"app\"}[$__rate_interval]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}