apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: UTIaISP4k
    url: http://hive-backend-prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      defaultEditor: code
      httpMethod: POST
