global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hive-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${HIVE_BACKEND_PROMETHEUS_HOST:localhost}:8080"]
