global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hive-backend"
    static_configs:
      - targets: ["localhost:8080", "hive-backend-app:8080"]
  # - job_name: "hive-backend-node-exporter"
  #   static_configs:
  #     - targets: ["hive-backend-node-exporter:9100"]
