global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["hive-backend-app:8080"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["hive-backend-cadvisor:9100"]
